apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: corewebapp-hpa
  namespace: default
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azure-k8s-corewebapp
  targetCPUUtilizationPercentage: 50 # target CPU utilization
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: azure-k8s-blazorapp-hpa
  namespace: default
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azure-k8s-blazorapp
  targetCPUUtilizationPercentage: 50 # target CPU utilization